### ISSUE TITLE
Make a more aesthetically pleasing color palette that will attract the eye.

### ISSUE THREAD

**Issue by jjessicahuangg** [iJianHuang/Best-Study-Notes#3]
For example, google.com uses a plain white background with grey and blue accents; very simple and minimalistic but very effective. Another example is Netflix.com which uses more dark hues to make viewers feel at ease when watching movies and tv shows (marketing !, know your customers, and know what will make them comfortable). Choose a few colors and tailor your website using those colors, because its usually what people notice first when they are on the internet. ALSOOOOO, I'm not sure what Stone Mountain has to do with audio notes, except for the fact that we live in Georgia....so maybe find a different image later O_O.

**Comment by iJianHuang** [comment]
work on changing the theme to dark mode first.

**Comment by iJianHuang** [comment]
It turned out that black theme was difficult because there were not much content to present. So switched to white / blue theme with black header and footer. In addition, changed the hover color in header and footer to light gray.
